import type {
  ArpgClassDefinition,
  ArpgEnemyDefinition,
  ArpgEquipmentSlot,
  ArpgItemDefinition,
  ArpgItemQuality,
  ArpgLootNodeDefinition,
  ArpgLoreNode,
  ArpgOriginDefinition,
  ArpgQuestDefinition,
  ArpgScenePropSlot,
  ArpgSkillDefinition,
  ArpgZoneDefinition,
} from "@/lib/arpgGame";
import {
  ARPG_PROLOGUE_FIRST_LOCATION,
  ARPG_PROLOGUE_FIRST_QUEST,
} from "@/lib/arpgPrologueContent";

export const ARPG_GAME_TITLE = "Aether Reliquary";
export const ARPG_ZONE_ID = "first-reliquary";

export const ARPG_WORLD_BOUNDS = {
  minX: -3.8,
  maxX: 3.8,
  minZ: -2.8,
  maxZ: 2.8,
};

export const ARPG_EQUIPMENT_SLOTS: ArpgEquipmentSlot[] = [
  "weapon",
  "offhand",
  "helm",
  "armor",
  "gloves",
  "boots",
  "relic",
  "sigil",
  "charm",
  "ring-left",
  "ring-right",
  "amulet",
];

export const ARPG_ITEM_QUALITIES: Record<
  ArpgItemQuality,
  { label: string; color: string; statMultiplier: number }
> = {
  common: { label: "Common", color: "#c9a46a", statMultiplier: 1 },
  uncommon: { label: "Uncommon", color: "#90be6d", statMultiplier: 1.12 },
  rare: { label: "Rare", color: "#ffd166", statMultiplier: 1.28 },
  epic: { label: "Epic", color: "#d946ef", statMultiplier: 1.52 },
  relic: { label: "Relic", color: "#8ecae6", statMultiplier: 1.78 },
  ancient: { label: "Ancient", color: "#f59e0b", statMultiplier: 2.08 },
  mythic: { label: "Mythic", color: "#fb7185", statMultiplier: 2.42 },
};

export const ARPG_ORIGINS: Record<string, ArpgOriginDefinition> = {
  wardbound: {
    id: "wardbound",
    name: "Wardbound",
    summary:
      "A reliquary oathkeeper built for patient fights, strong wards, and careful relic work.",
    baseStats: {
      might: 8,
      ward: 12,
      focus: 9,
      speed: 7,
      crit: 3,
      cooldown: 2,
      resonance: 5,
    },
  },
  "ash-cartographer": {
    id: "ash-cartographer",
    name: "Ash Cartographer",
    summary:
      "A mapmaker of ruined machines, faster through vaults and better at uncovering old routes.",
    baseStats: {
      might: 6,
      ward: 8,
      focus: 13,
      speed: 10,
      crit: 5,
      cooldown: 4,
      resonance: 7,
    },
  },
  "rune-vagrant": {
    id: "rune-vagrant",
    name: "Rune Vagrant",
    summary:
      "A wandering sigil-breaker with unstable power and a knack for awakening dead systems.",
    baseStats: {
      might: 10,
      ward: 7,
      focus: 10,
      speed: 9,
      crit: 6,
      cooldown: 3,
      resonance: 6,
    },
  },
};

export const ARPG_CLASS_PATHS: Record<string, ArpgClassDefinition> = {
  wardbreaker: {
    id: "wardbreaker",
    name: "Wardbreaker",
    summary:
      "Front-line oath combat: heavy strikes, guard windows, and bonus might from upgraded gear.",
    accent: "#f4a261",
    starterSkillId: "wardbreaker-cleave",
  },
  relicweaver: {
    id: "relicweaver",
    name: "Relicweaver",
    summary:
      "Machine-mystic control: focus surges, relic resonance, and stronger interaction rewards.",
    accent: "#8ecae6",
    starterSkillId: "relicweaver-surge",
  },
  ashrunner: {
    id: "ashrunner",
    name: "Ashrunner",
    summary:
      "Mobile skirmisher play: speed, crit pressure, and fast repositioning around old traps.",
    accent: "#90be6d",
    starterSkillId: "ashrunner-dash",
  },
};

export const ARPG_SKILLS: Record<string, ArpgSkillDefinition> = {
  "wardbreaker-cleave": {
    id: "wardbreaker-cleave",
    pathId: "wardbreaker",
    name: "Cinder Cleave",
    kind: "active",
    unlockLevel: 1,
    summary:
      "A reliable arc strike that adds might scaling to the next attack.",
    statBonus: { might: 2 },
    cooldownMs: 1600,
    accent: "#f4a261",
  },
  "wardbreaker-guard": {
    id: "wardbreaker-guard",
    pathId: "wardbreaker",
    name: "Bronze Guard",
    kind: "passive",
    unlockLevel: 2,
    summary: "Upgraded armor and shields grant extra ward.",
    statBonus: { ward: 4 },
    cooldownMs: 0,
    accent: "#c9a46a",
  },
  "relicweaver-surge": {
    id: "relicweaver-surge",
    pathId: "relicweaver",
    name: "Loom Surge",
    kind: "active",
    unlockLevel: 1,
    summary: "Spend focus to pulse relic energy through nearby constructs.",
    statBonus: { focus: 2, resonance: 2 },
    cooldownMs: 1800,
    accent: "#8ecae6",
  },
  "relicweaver-tuning": {
    id: "relicweaver-tuning",
    pathId: "relicweaver",
    name: "Fine Tuning",
    kind: "passive",
    unlockLevel: 2,
    summary: "Relics and charms gain extra resonance after upgrades.",
    statBonus: { focus: 3, resonance: 3 },
    cooldownMs: 0,
    accent: "#7dd3fc",
  },
  "ashrunner-dash": {
    id: "ashrunner-dash",
    pathId: "ashrunner",
    name: "Ash Step",
    kind: "active",
    unlockLevel: 1,
    summary:
      "A short repositioning burst that keeps combat readable and quick.",
    statBonus: { speed: 2 },
    cooldownMs: 1400,
    accent: "#90be6d",
  },
  "ashrunner-footwork": {
    id: "ashrunner-footwork",
    pathId: "ashrunner",
    name: "Soot Footwork",
    kind: "passive",
    unlockLevel: 2,
    summary: "Movement speed adds a little crit pressure.",
    statBonus: { speed: 2, crit: 2 },
    cooldownMs: 0,
    accent: "#a7f3d0",
  },
};

export const ARPG_ITEMS: Record<string, ArpgItemDefinition> = {
  "cinder-glaive": {
    id: "cinder-glaive",
    name: "Cinder Glaive",
    type: "equipment",
    slot: "weapon",
    quality: "common",
    rarity: "common",
    summary: "A warm polearm with a reactor ember sealed below the blade.",
    lore: "Its edge remembers the first wardens who carved safe rooms out of the dark.",
    stats: { might: 7, focus: 1 },
    accent: "#f4a261",
  },
  "ember-buckler": {
    id: "ember-buckler",
    name: "Ember Buckler",
    type: "equipment",
    slot: "offhand",
    quality: "common",
    rarity: "common",
    summary: "A small shield with a furnace coin bolted under the grip.",
    lore: "It was designed for scouts who needed both hands free and one miracle nearby.",
    stats: { ward: 4, crit: 1 },
    accent: "#c9a46a",
  },
  "pilgrim-helm": {
    id: "pilgrim-helm",
    name: "Pilgrim Helm",
    type: "equipment",
    slot: "helm",
    quality: "common",
    rarity: "common",
    summary: "A dented bronze helm with a narrow amber visor.",
    lore: "The visor warms when a spoken oath is still true.",
    stats: { ward: 3, focus: 1 },
    accent: "#d6a85f",
  },
  "threadbare-wardplate": {
    id: "threadbare-wardplate",
    name: "Threadbare Wardplate",
    type: "equipment",
    slot: "armor",
    quality: "common",
    rarity: "common",
    summary: "Old bronze plating laced with still-working defensive thread.",
    lore: "Every scar on the plate is tagged with a tiny repair-rune.",
    stats: { ward: 8 },
    accent: "#c9a46a",
  },
  "ash-runner-boots": {
    id: "ash-runner-boots",
    name: "Ash-Runner Boots",
    type: "equipment",
    slot: "boots",
    quality: "common",
    rarity: "common",
    summary: "Soft boots made for crossing hot stone without waking the floor.",
    lore: "The soles are stitched with tiny route calculations.",
    stats: { speed: 4 },
    accent: "#90be6d",
  },
  "oath-stitch-gloves": {
    id: "oath-stitch-gloves",
    name: "Oath-Stitch Gloves",
    type: "equipment",
    slot: "gloves",
    quality: "common",
    rarity: "common",
    summary: "Plain work gloves stitched with one stubborn oath thread.",
    lore: "They were made for hammer handles, lamp chains, and holding on when the city shakes.",
    stats: { might: 1, cooldown: 1 },
    accent: "#c9a46a",
  },
  "memory-prism": {
    id: "memory-prism",
    name: "Memory Prism",
    type: "equipment",
    slot: "relic",
    quality: "common",
    rarity: "common",
    summary: "A palm-sized prism that hums near forgotten architecture.",
    lore: "The prism stores echoes, not answers. It is friendlier that way.",
    stats: { focus: 6, resonance: 2 },
    accent: "#8ecae6",
  },
  "wayfinder-sigil": {
    id: "wayfinder-sigil",
    name: "Wayfinder Sigil",
    type: "equipment",
    slot: "sigil",
    quality: "common",
    rarity: "common",
    summary: "A brass token that warms when a route is safe enough to risk.",
    lore: "It points toward thresholds, not destinations.",
    stats: { speed: 2, ward: 2 },
    accent: "#90be6d",
  },
  "brass-charm": {
    id: "brass-charm",
    name: "Brass Charm",
    type: "equipment",
    slot: "charm",
    quality: "common",
    rarity: "common",
    summary: "A humble charm for keeping strange doors polite.",
    lore: "It has no teeth, but it remembers where teeth should be.",
    stats: { resonance: 2, ward: 1 },
    accent: "#d6a85f",
  },
  "copper-oath-ring": {
    id: "copper-oath-ring",
    name: "Copper Oath Ring",
    type: "equipment",
    slot: "ring-left",
    quality: "common",
    rarity: "common",
    summary: "A modest civic ring that warms when a promise is witnessed.",
    lore: "It is too plain to impress anyone. That is why Veyrhold trusts it.",
    stats: { ward: 1, focus: 1 },
    accent: "#c9a46a",
  },
  "pilgrim-tin-ring": {
    id: "pilgrim-tin-ring",
    name: "Pilgrim Tin Ring",
    type: "equipment",
    slot: "ring-right",
    quality: "common",
    rarity: "common",
    summary: "A traveler's ring stamped with a small road mark.",
    lore: "Every pilgrim claims the mark points home. It mostly points forward.",
    stats: { speed: 1, resonance: 1 },
    accent: "#d6a85f",
  },
  "bellroot-cord-amulet": {
    id: "bellroot-cord-amulet",
    name: "Bellroot Cord Amulet",
    type: "equipment",
    slot: "amulet",
    quality: "common",
    rarity: "common",
    summary:
      "A cord-and-brass amulet given to people who descend before they understand why.",
    lore: "The knot is simple. The oath tied into it is not.",
    stats: { ward: 1, resonance: 2 },
    accent: "#f4a261",
  },
  "loomshard-charm": {
    id: "loomshard-charm",
    name: "Loom-Shard Charm",
    type: "equipment",
    slot: "charm",
    quality: "rare",
    rarity: "rare",
    summary:
      "A living shard from the reliquary loom. It sharpens memory and wardwork.",
    lore: "The charm clicks softly when an old door decides you are worth hearing.",
    stats: { focus: 10, ward: 3, resonance: 5 },
    accent: "#ffd166",
  },
  "oracle-focus": {
    id: "oracle-focus",
    name: "Oracle Focus",
    type: "equipment",
    slot: "offhand",
    quality: "uncommon",
    rarity: "uncommon",
    summary: "A hovering lens that helps the oracle mark nearby choices.",
    lore: "Its glass carries a patient voice under the hum.",
    stats: { focus: 5, cooldown: 2 },
    accent: "#7dd3fc",
  },
  "warden-cuirass": {
    id: "warden-cuirass",
    name: "Warden Cuirass",
    type: "equipment",
    slot: "armor",
    quality: "epic",
    rarity: "epic",
    summary: "A heavy chest piece stamped with the Brass Warden's oath-seal.",
    lore: "It does not forgive a bad stance. It does forgive surviving.",
    stats: { ward: 13, might: 4, resonance: 3 },
    accent: "#d946ef",
  },
  "veyrhold-banner-spear": {
    id: "veyrhold-banner-spear",
    name: "Veyrhold Banner Spear",
    type: "equipment",
    slot: "weapon",
    quality: "rare",
    rarity: "rare",
    summary:
      "A city-oath spear tuned for reach, ward stance, and early socket planning.",
    lore: "The brass pennant rings once when a promise is kept and twice when it is tested.",
    stats: { might: 8, ward: 4, speed: 3, resonance: 2 },
    accent: "#ffd166",
  },
  "lenswright-stiletto": {
    id: "lenswright-stiletto",
    name: "Lenswright Stiletto",
    type: "equipment",
    slot: "weapon",
    quality: "epic",
    rarity: "epic",
    summary:
      "A mirrored dagger built for crit pressure, quick steps, and clean status windows.",
    lore: "It leaves a reflection behind to apologize for the cut.",
    stats: { might: 5, speed: 8, crit: 8, cooldown: 3 },
    accent: "#d946ef",
  },
  "brass-warden-glaive": {
    id: "brass-warden-glaive",
    name: "Brass Warden Glaive",
    type: "equipment",
    slot: "weapon",
    quality: "relic",
    rarity: "relic",
    summary:
      "A boss-forged polearm with heavy stagger identity and double-socket planning.",
    lore: "The Brass Warden did not drop it. The oath decided to follow you instead.",
    stats: { might: 13, ward: 6, resonance: 7 },
    accent: "#8ecae6",
  },
  "auric-sunstaff": {
    id: "auric-sunstaff",
    name: "Auric Sunstaff",
    type: "equipment",
    slot: "weapon",
    quality: "ancient",
    rarity: "ancient",
    summary:
      "An ancient focus staff for holy pressure, cooldown recovery, and relic resonance.",
    lore: "Its gold is not metal. It is stored daylight with a handle.",
    stats: { focus: 14, ward: 6, cooldown: 8, resonance: 12 },
    accent: "#f59e0b",
  },
  "crownless-scythe": {
    id: "crownless-scythe",
    name: "Crownless Scythe",
    type: "equipment",
    slot: "weapon",
    quality: "mythic",
    rarity: "mythic",
    summary:
      "A mythic endgame scythe for curse builds, crit windows, and relic resonance spikes.",
    lore: "It cuts commands away from kings and lets the silence decide what remains.",
    stats: { might: 16, focus: 8, crit: 10, resonance: 14 },
    accent: "#fb7185",
  },
  "warden-chain-flail": {
    id: "warden-chain-flail",
    name: "Warden Chain-Flail",
    type: "equipment",
    slot: "weapon",
    quality: "epic",
    rarity: "epic",
    summary:
      "An anti-guard flail that rewards close timing and shield-breaking pressure.",
    lore: "Every chain link has a tiny ward-drill etched into the brass.",
    stats: { might: 11, ward: 5, crit: 5, resonance: 3 },
    accent: "#d946ef",
  },
  "bellroot-cleaver": {
    id: "bellroot-cleaver",
    name: "Bellroot Cleaver",
    type: "equipment",
    slot: "weapon",
    quality: "rare",
    rarity: "rare",
    summary:
      "A heavy civic blade that trades speed for might, ward posture, and cleave weight.",
    lore: "The Bellroot smiths call it a sword because calling it a door-opener sounds impolite.",
    stats: { might: 12, ward: 4, crit: 2 },
    accent: "#ffd166",
  },
  "health-vial": {
    id: "health-vial",
    name: "Health Vial",
    type: "consumable",
    quality: "common",
    rarity: "common",
    maxStack: 9,
    summary: "A bitter red restorative brewed in a reliquary burner.",
    lore: "Warm enough to be comforting. Strong enough to be rude.",
    stats: {},
    effect: { hp: 35 },
    accent: "#ef4444",
  },
  "focus-draught": {
    id: "focus-draught",
    name: "Focus Draught",
    type: "consumable",
    quality: "uncommon",
    rarity: "uncommon",
    maxStack: 6,
    summary: "A blue-gold tonic that steadies relic casting.",
    lore: "Every sip tastes like rain on old copper.",
    stats: {},
    effect: { mana: 25 },
    accent: "#8ecae6",
  },
  "upgrade-shard": {
    id: "upgrade-shard",
    name: "Upgrade Shard",
    type: "material",
    quality: "common",
    rarity: "common",
    maxStack: 99,
    summary: "A raw shard used for +1 through +5 gear tempering.",
    lore: "It wants to become an edge, a stitch, or a lockpick.",
    stats: {},
    accent: "#ffd166",
  },
  "relic-dust": {
    id: "relic-dust",
    name: "Relic Dust",
    type: "material",
    quality: "rare",
    rarity: "rare",
    maxStack: 99,
    summary: "Fine luminous dust needed for higher-rank upgrades.",
    lore: "The old machines shed it like pollen.",
    stats: {},
    accent: "#d946ef",
  },
  "rare-catalyst": {
    id: "rare-catalyst",
    name: "Rare Catalyst",
    type: "material",
    quality: "rare",
    rarity: "rare",
    maxStack: 99,
    summary: "A boss-grade spark used for endgame recipes and rematch rewards.",
    lore: "It refuses to cool because it remembers the fight that made it.",
    stats: {},
    accent: "#fb7185",
  },
  "monster-part": {
    id: "monster-part",
    name: "Monster Part",
    type: "material",
    quality: "uncommon",
    rarity: "uncommon",
    maxStack: 99,
    summary:
      "Claw, moss, ash, shell, or bone used for repeatable field crafting.",
    lore: "The reliquary catalogs it politely. The bag does not.",
    stats: {},
    accent: "#90be6d",
  },
  "city-scrip": {
    id: "city-scrip",
    name: "City Scrip",
    type: "material",
    quality: "uncommon",
    rarity: "uncommon",
    maxStack: 99,
    summary:
      "Local reputation currency traded for city sets and endgame route favors.",
    lore: "Each city mints promises in a different shape.",
    stats: {},
    accent: "#facc15",
  },
  "gate-key-fragment": {
    id: "gate-key-fragment",
    name: "Gate Key Fragment",
    type: "quest",
    quality: "relic",
    rarity: "relic",
    maxStack: 3,
    summary: "One piece of the key that wakes the locked north exit.",
    lore: "It has more memory than metal.",
    stats: {},
    accent: "#8ecae6",
  },
};

export const ARPG_STARTER_ITEM_IDS = [
  "cinder-glaive",
  "ember-buckler",
  "pilgrim-helm",
  "threadbare-wardplate",
  "ash-runner-boots",
  "oath-stitch-gloves",
  "memory-prism",
  "wayfinder-sigil",
  "brass-charm",
  "copper-oath-ring",
  "pilgrim-tin-ring",
  "bellroot-cord-amulet",
  "health-vial",
  "focus-draught",
  "upgrade-shard",
];

export const ARPG_STARTER_EQUIPMENT: Record<ArpgEquipmentSlot, string | null> =
  {
    weapon: "cinder-glaive",
    offhand: "ember-buckler",
    helm: "pilgrim-helm",
    armor: "threadbare-wardplate",
    gloves: "oath-stitch-gloves",
    boots: "ash-runner-boots",
    relic: "memory-prism",
    sigil: "wayfinder-sigil",
    charm: "brass-charm",
    "ring-left": "copper-oath-ring",
    "ring-right": "pilgrim-tin-ring",
    amulet: "bellroot-cord-amulet",
  };

export const ARPG_LOOT_PEDESTAL_ITEM_ID = "loomshard-charm";

export const ARPG_LOOT_NODES: Record<string, ArpgLootNodeDefinition> = {
  "loomshard-pedestal": {
    id: "loomshard-pedestal",
    title: "Loom-Shard Pedestal",
    itemId: ARPG_LOOT_PEDESTAL_ITEM_ID,
    quantity: 1,
    summary:
      "A memory charm turns above the altar. It is the first relic hook, not the first weapon.",
    position: { x: -0.45, z: -1.52 },
  },
  "forge-cache": {
    id: "forge-cache",
    title: "Forge Cache",
    itemId: "upgrade-shard",
    quantity: 2,
    summary:
      "A cracked reliquary locker stores upgrade shards for the first temper.",
    position: { x: 2.2, z: 1.45 },
  },
  "oracle-cache": {
    id: "oracle-cache",
    title: "Oracle Cache",
    itemId: "oracle-focus",
    quantity: 1,
    summary: "A companion lens waits inside a blue archive alcove.",
    position: { x: -2.35, z: 0.55 },
  },
  "north-key-fragment": {
    id: "north-key-fragment",
    title: "Gate Fragment",
    itemId: "gate-key-fragment",
    quantity: 1,
    summary: "A key fragment rests beside the locked north door.",
    position: { x: 0.2, z: -2.48 },
  },
};

export const ARPG_ENEMIES: Record<string, ArpgEnemyDefinition> = {
  "hollow-sentry": {
    id: "hollow-sentry",
    name: "Hollow Sentry",
    summary: "A low-risk training construct guarding the reliquary gate.",
    familyId: "hollow-sentries",
    spriteFrameId: "hollow-sentry",
    maxHp: 44,
    xp: 24,
    gold: 7,
    level: 1,
    position: { x: 1.72, z: -1.18 },
    drops: [
      { itemId: "upgrade-shard", chance: 1, quantity: 1 },
      { itemId: "veyrhold-banner-spear", chance: 1, quantity: 1 },
    ],
  },
  "ashling-scout": {
    id: "ashling-scout",
    name: "Ashling Scout",
    summary: "A small ember-thing that darts between cracked floor seams.",
    familyId: "ash-fiends",
    spriteFrameId: "ashling-scout",
    maxHp: 32,
    xp: 18,
    gold: 5,
    level: 1,
    position: { x: -2.25, z: 0.9 },
    drops: [
      { itemId: "health-vial", chance: 1, quantity: 1 },
      { itemId: "lenswright-stiletto", chance: 1, quantity: 1 },
    ],
  },
  "rune-husk": {
    id: "rune-husk",
    name: "Rune Husk",
    summary: "A slow shell of bad instructions and old brass bones.",
    familyId: "rune-husks",
    spriteFrameId: "rune-husk",
    maxHp: 62,
    xp: 36,
    gold: 10,
    level: 2,
    position: { x: 2.35, z: 0.55 },
    drops: [
      { itemId: "relic-dust", chance: 1, quantity: 1 },
      { itemId: "bellroot-cleaver", chance: 1, quantity: 1 },
    ],
  },
  "brass-warden": {
    id: "brass-warden",
    name: "The Brass Warden",
    summary: "The first mini-boss, oath-locked behind the forge lesson.",
    familyId: "hollow-sentries",
    spriteFrameId: "brass-warden",
    maxHp: 96,
    xp: 58,
    gold: 22,
    level: 3,
    position: { x: 0.35, z: -2.12 },
    drops: [
      { itemId: "warden-cuirass", chance: 1, quantity: 1 },
      { itemId: "gate-key-fragment", chance: 1, quantity: 1 },
      { itemId: "brass-warden-glaive", chance: 1, quantity: 1 },
    ],
    requiresStoryFlags: ["lore:gate-monolith", "equipped:loomshard-charm"],
    requiresUpgradedItem: true,
  },
  "ember-mote": {
    id: "ember-mote",
    name: "Ember Mote",
    summary:
      "A furnace-born spark that tries to stack burn before the hero can breathe.",
    familyId: "ash-fiends",
    spriteFrameId: "ember-mote",
    maxHp: 28,
    xp: 16,
    gold: 4,
    level: 1,
    position: { x: -1.75, z: -0.65 },
    drops: [
      { itemId: "focus-draught", chance: 1, quantity: 1 },
      { itemId: "warden-chain-flail", chance: 1, quantity: 1 },
    ],
  },
  "glass-gnawer": {
    id: "glass-gnawer",
    name: "Glass Gnawer",
    summary:
      "A mirror-bitten crawler that leaves tiny cuts in the air before it lunges.",
    familyId: "glass-wraiths",
    spriteFrameId: "glass-gnawer",
    maxHp: 48,
    xp: 30,
    gold: 9,
    level: 2,
    position: { x: 1.15, z: 1.65 },
    drops: [{ itemId: "health-vial", chance: 1, quantity: 1 }],
  },
};

export const ARPG_LORE_NODES: Record<string, ArpgLoreNode> = {
  "descent-ledger": {
    id: "descent-ledger",
    title: "Descent Ledger",
    summary:
      "A brass-root civic ledger records the hero's player-created name, lineage, class, and first visible identity.",
    position: { x: -1.28, z: 1.08 },
    storyFlag: "lore:descent-ledger",
  },
  "oath-lamp-arcade": {
    id: "oath-lamp-arcade",
    title: "Oath-Lamp Arcade",
    summary:
      "A curved row of amber lamps teaches movement and inspection before the reliquary reveals danger.",
    position: { x: -2.72, z: 0.06 },
    storyFlag: "lore:oath-lamp-arcade",
  },
  "gate-monolith": {
    id: "gate-monolith",
    title: "Gate Monolith",
    summary:
      "A black-stone machine recognizes the hero as a living witness: name player-kept, oath unbroken, road listening.",
    position: { x: -2.2, z: -1.35 },
    storyFlag: "lore:gate-monolith",
  },
  "forge-echo": {
    id: "forge-echo",
    title: "Relic-Forge Echo",
    summary:
      "A half-awake forge teaches the first upgrade ritual: shard, oath, pressure, heat.",
    position: { x: 2.45, z: 1.52 },
    storyFlag: "lore:forge-echo",
  },
  "oracle-companion": {
    id: "oracle-companion",
    title: "Oracle Companion",
    summary:
      "Ilo wakes in a blue-glass cradle, jokes about counting the quiet, and starts marking useful choices.",
    position: { x: -0.95, z: 0.28 },
    storyFlag: "npc:oracle-met",
  },
};

export const ARPG_QUESTS: Record<string, ArpgQuestDefinition> = {
  "awaken-the-reliquary": {
    id: "awaken-the-reliquary",
    title: ARPG_PROLOGUE_FIRST_QUEST.title,
    summary: ARPG_PROLOGUE_FIRST_QUEST.summary,
    steps: ARPG_PROLOGUE_FIRST_QUEST.steps,
    requiredFlags: ARPG_PROLOGUE_FIRST_QUEST.requiredFlags,
    rewardItemIds: ["upgrade-shard"],
  },
  "temper-a-relic": {
    id: "temper-a-relic",
    title: "Temper a Relic",
    summary: "Use the forge cache to upgrade one equipped item.",
    steps: ["Open the Forge Cache.", "Upgrade any equipped item to +1."],
    requiredFlags: ["opened:forge-cache", "upgraded:any"],
    rewardItemIds: ["relic-dust"],
  },
  "quiet-the-warden": {
    id: "quiet-the-warden",
    title: "Quiet the Brass Warden",
    summary:
      "Defeat the mini-boss and claim a gate fragment for the next chamber.",
    steps: [
      "Defeat the Hollow Sentry.",
      "Defeat the Brass Warden.",
      "Collect a Gate Key Fragment.",
    ],
    requiredFlags: [
      "defeated:hollow-sentry",
      "defeated:brass-warden",
      "loot:gate-key-fragment",
    ],
    rewardItemIds: ["warden-cuirass"],
  },
};

export const ARPG_FIRST_ZONE: ArpgZoneDefinition = {
  id: ARPG_ZONE_ID,
  name: "The First Reliquary",
  summary: `${ARPG_PROLOGUE_FIRST_LOCATION.name}: ${ARPG_PROLOGUE_FIRST_LOCATION.visualSummary}`,
  spawn: { x: -0.8, z: 0.95 },
  rooms: [
    {
      id: "gate-room",
      label: "Bellroot Vestibule",
      center: { x: -0.3, z: 0.65 },
      radius: 1.45,
    },
    {
      id: "archive-alcove",
      label: "Namewell Alcove",
      center: { x: -2.25, z: 0.42 },
      radius: 0.86,
    },
    {
      id: "forge-pedestal",
      label: "Quiet Forge Pedestal",
      center: { x: 2.32, z: 1.33 },
      radius: 0.82,
    },
    {
      id: "sentry-hall",
      label: "Warden's Antechamber",
      center: { x: 1.55, z: -1.08 },
      radius: 1.02,
    },
    {
      id: "north-exit",
      label: "Sealed North Road",
      center: { x: 0.25, z: -2.35 },
      radius: 0.72,
    },
  ],
  obstacles: [
    {
      id: "west-wall",
      label: "west wall",
      x: -3.95,
      z: 0,
      width: 0.35,
      depth: 5.65,
    },
    {
      id: "east-wall",
      label: "east wall",
      x: 3.95,
      z: 0,
      width: 0.35,
      depth: 5.65,
    },
    {
      id: "north-wall",
      label: "north wall",
      x: 0,
      z: -3.02,
      width: 7.6,
      depth: 0.32,
    },
    {
      id: "south-rubble",
      label: "south rubble",
      x: 1.55,
      z: 2.18,
      width: 1.2,
      depth: 0.34,
    },
    {
      id: "archive-column",
      label: "archive column",
      x: -2.95,
      z: 0.42,
      width: 0.42,
      depth: 0.42,
    },
    {
      id: "east-column",
      label: "east column",
      x: 2.78,
      z: 0.72,
      width: 0.42,
      depth: 0.42,
    },
  ],
};

export const ARPG_SCENE_PROP_SLOTS: ArpgScenePropSlot[] = [
  {
    id: "north-gate-arch",
    assetId: "procedural-rune-gate-arch",
    role: "portal",
    label: "sealed north reliquary arch",
    position: { x: 0.2, z: -2.35 },
    scale: 1.1,
  },
  {
    id: "west-broken-column",
    assetId: "procedural-broken-column",
    role: "architecture",
    label: "weathered column fragment",
    position: { x: -2.95, z: 0.45 },
    rotationY: 0.22,
    scale: 0.92,
  },
  {
    id: "east-broken-column",
    assetId: "procedural-broken-column",
    role: "architecture",
    label: "weathered column fragment",
    position: { x: 2.72, z: 0.72 },
    rotationY: -0.38,
    scale: 1.08,
  },
  {
    id: "south-rune-brazier",
    assetId: "procedural-rune-brazier",
    role: "light",
    label: "amber rune brazier",
    position: { x: -1.72, z: 1.88 },
    scale: 0.86,
  },
  {
    id: "east-rune-brazier",
    assetId: "procedural-rune-brazier",
    role: "light",
    label: "blue rune brazier",
    position: { x: 2.36, z: -0.78 },
    scale: 0.76,
  },
  {
    id: "south-relic-crates",
    assetId: "procedural-relic-crate-cluster",
    role: "set-dressing",
    label: "reliquary salvage crates",
    position: { x: 1.6, z: 1.84 },
    rotationY: 0.42,
    scale: 0.9,
  },
];
