/* eslint-disable no-console */
/**
 * Auto-generate a compact Codex-first handoff from current repo state.
 *
 * Primary outputs:
 * - docs/AGENT_HANDOFF.md
 * - docs/CODEX_HANDOFF.md
 *
 * Lightweight compatibility pointers:
 * - docs/CLAUDE_HANDOFF.md
 * - docs/CURSOR_HANDOFF.md
 *
 * Goals:
 * - Stable output (no per-commit SHA / file-list/env-dependent churn).
 * - Codex-oriented restart context without duplicating long mirrors.
 * - Todo + supplement + enough context to continue work immediately.
 *
 * Usage:
 *   node scripts/generate-handoff.js --write
 *   node scripts/generate-handoff.js --check
 */

const fs = require("node:fs");
const path = require("node:path");

function parseTodoItem(line) {
  const normalized = line.trim().replace("- [ ] ", "");
  const match = normalized.match(/^([^—]+?)\s+—\s+(.+)$/);
  if (!match) return { id: normalized, text: "" };
  return { id: match[1].trim(), text: match[2].trim() };
}

function getTodoRoot(id) {
  return id.match(/^[A-Z]+\d+/)?.[0] ?? id;
}

function formatTodoItem(item) {
  if (!item.text) return `- ${item.id}`;
  const maxLength = 220;
  const text =
    item.text.length > maxLength
      ? `${item.text.slice(0, maxLength).replace(/\s+\S*$/, "")}...`
      : item.text;
  return `- ${item.id} — ${text}`;
}

function getTopTodoLines(todoPathAbs) {
  const raw = fs.readFileSync(todoPathAbs, "utf8");
  const lines = raw.split(/\r?\n/);
  const start = lines.findIndex((l) => l.trim() === "## Next Up");
  if (start === -1) return [];
  const items = [];
  for (let i = start + 1; i < lines.length; i++) {
    const l = lines[i];
    if (l.startsWith("## ")) break;
    if (l.trim().startsWith("- [ ] ")) items.push(parseTodoItem(l));
  }

  if (!items.length) return [];

  const [first, ...rest] = items;
  const firstRoot = getTodoRoot(first.id);
  const childCount = rest.filter(
    (item) => getTodoRoot(item.id) === firstRoot,
  ).length;
  const distinctNext = rest
    .filter((item) => getTodoRoot(item.id) !== firstRoot)
    .slice(0, 2);

  const out = [formatTodoItem(first)];
  if (childCount > 0) {
    out.push(
      `- ${firstRoot} child tracks — ${childCount} follow-up tracks are queued in \`tasks/todo.md\`; expand there when implementing.`,
    );
  }
  out.push(...distinctNext.map(formatTodoItem));
  out.push("- Full queue: `tasks/todo.md` -> `## Next Up`.");

  return out;
}

function buildHandoff() {
  const repoRoot = process.cwd();

  const packageJson = JSON.parse(
    fs.readFileSync(path.join(repoRoot, "package.json"), "utf8"),
  );
  const verifyCmd = packageJson?.scripts?.verify
    ? "npm run verify"
    : "npx tsc --noEmit";
  const devCmd = packageJson?.scripts?.dev ? "npm run dev" : "npm run dev";

  const todoAbs = path.join(repoRoot, "tasks", "todo.md");
  const nextUp = fs.existsSync(todoAbs) ? getTopTodoLines(todoAbs) : [];

  const supplementPath = path.join(repoRoot, "docs", "handoff-supplement.md");
  const supplement = fs.existsSync(supplementPath)
    ? "\n" +
      String(fs.readFileSync(supplementPath, "utf8"))
        .replace(/\r\n/g, "\n")
        .trim() +
      "\n"
    : "";

  const handoff = [
    "## Nexus Prime — Codex Handoff (AUTO)",
    "",
    "**Regenerated by:** `scripts/generate-handoff.js` (`npm run handoff:write`).",
    "Primary paths: `docs/AGENT_HANDOFF.md` and `docs/CODEX_HANDOFF.md`.",
    "Claude/Cursor compatibility files are intentionally short pointers so Codex stays the primary working handoff.",
    "Per-commit message / SHA / file lists are **omitted** here so this file stays stable across handoff-only commits.",
    "",
    "### Start here",
    "",
    "1. Run `npm run handoff:pull`.",
    "2. Read `AGENTS.md`, `docs/SYSTEM_STATE.md`, `tasks/todo.md` -> `## Next Up`, and `tasks/lessons.md`.",
    "3. Make the smallest safe change, verify, then run `npm run handoff:write` and `npm run handoff:check` when docs/state changed.",
    "",
    "### Project pulse",
    "",
    "- Nexus Prime is a local-first, self-hosted command-and-intelligence dashboard for markets, cyber, recon, resources, and operator AI.",
    "- Next.js 14 app is the active surface (`app/`, `components/`, `lib/`, `store/`).",
    "- `nexus-final.html` remains as legacy reference and should stay single-file.",
    "- Current product push is Homefront command-intelligence polish; the `/hq` RPG world is a personal/private lane and should not be used as public Nexus positioning.",
    "",
    "### Machine + commands",
    "",
    "- Primary machine: Windows + PowerShell. Avoid Bash-only chained syntax in repo instructions.",
    `- Install/run: \`npm install\`, then \`${devCmd}\`.`,
    `- Required verification after code changes: \`${verifyCmd}\`.`,
    "- Handoff sync after docs/task state changes: `npm run handoff:write`, then `npm run handoff:check`.",
    "",
    "### Security + ops constraints",
    "",
    "- Secrets live in `.env.local` (never commit). See `.env.example`.",
    "- Server routes are protected by `NEXUS_TOKEN` and CSP is enforced in `next.config.js`.",
    "- Prefer server-side API routes for external fetches to avoid CSP/CORS issues.",
    "- All AI provider access goes through `lib/ai.ts`; do not call providers directly.",
    "- Use Zustand selectors such as `useStore(s => s.field)`, not `useStore().field`.",
    "",
    "### What’s next (from `tasks/todo.md`)",
    "",
    ...(nextUp.length ? nextUp : ["- Review `tasks/todo.md` → `## Next Up`"]),
    "",
    "### Where to look",
    "",
    "- **Tabs**: `app/[tab]/page.tsx`",
    "- **State**: `store/useStore.ts`",
    "- **AI**: `lib/agent.ts`, `lib/ai.ts`, `app/api/ai/*`, `app/api/tools/*`",
    "- **Diagnostics**: `app/api/status/*`, `app/api/verify/*`, `docs/metrics/*`",
    "- **Deployment / ideas:** `docs/deployment/`, `docs/ideas/assimilated-ecosystem.md`, `Dockerfile`",
    "",
    ...(supplement
      ? ["### Continuation notes (committed supplement)", "", supplement]
      : []),
  ].join("\n");

  return handoff;
}

function buildCompatibilityHandoff(targetName) {
  return [
    `## Nexus Prime — ${targetName} Compatibility Pointer (AUTO)`,
    "",
    "**Regenerated by:** `scripts/generate-handoff.js` (`npm run handoff:write`).",
    "",
    "This repo is now operated primarily through Codex, so this compatibility file stays intentionally short.",
    "",
    "Read instead:",
    "- `docs/AGENT_HANDOFF.md` — compact canonical restart handoff.",
    "- `docs/CODEX_HANDOFF.md` — same Codex-first handoff for Codex-native sessions.",
    "- `AGENTS.md`, `docs/SYSTEM_STATE.md`, `tasks/todo.md`, and `tasks/lessons.md` — live context spine.",
    "",
    "Do not expand this mirror unless Mario explicitly asks to revive Claude/Cursor-first workflows.",
  ].join("\n");
}

function normalizeNewlines(s) {
  return s.replace(/\r\n/g, "\n");
}

function getHandoffOutputs() {
  const repoRoot = process.cwd();
  const primary = normalizeNewlines(buildHandoff()).trim() + "\n";
  return [
    { path: path.join(repoRoot, "docs", "AGENT_HANDOFF.md"), content: primary },
    { path: path.join(repoRoot, "docs", "CODEX_HANDOFF.md"), content: primary },
    {
      path: path.join(repoRoot, "docs", "CLAUDE_HANDOFF.md"),
      content:
        normalizeNewlines(buildCompatibilityHandoff("Claude")).trim() + "\n",
    },
    {
      path: path.join(repoRoot, "docs", "CURSOR_HANDOFF.md"),
      content:
        normalizeNewlines(buildCompatibilityHandoff("Cursor")).trim() + "\n",
    },
  ];
}

function main() {
  const args = process.argv.slice(2);
  const write = args.includes("--write");
  const check = args.includes("--check");
  if (!write && !check) {
    console.error("Usage: node scripts/generate-handoff.js --write|--check");
    process.exit(2);
  }

  const outputs = getHandoffOutputs();

  if (check) {
    const stale = outputs
      .filter((out) => {
        const cur = fs.existsSync(out.path)
          ? normalizeNewlines(fs.readFileSync(out.path, "utf8"))
          : "";
        return normalizeNewlines(cur) !== out.content;
      })
      .map((out) => out.path);
    if (stale.length) {
      console.error(
        `${stale.join(", ")} ${stale.length === 1 ? "is" : "are"} stale. Run: npm run handoff:write`,
      );
      process.exit(1);
    }
    console.log(
      "Handoff OK: Codex handoff and compatibility pointers are up to date.",
    );
    return;
  }

  for (const out of outputs) {
    fs.mkdirSync(path.dirname(out.path), { recursive: true });
    fs.writeFileSync(out.path, out.content, "utf8");
    console.log(`Wrote ${out.path}`);
  }
}

main();
