/* eslint-disable no-console */
/**
 * Auto-generate thin compatibility handoff files from the canonical context spine.
 *
 * Canonical output:
 * - docs/AGENT_HANDOFF.md
 *
 * Compatibility copies:
 * - docs/CLAUDE_HANDOFF.md
 * - docs/CODEX_HANDOFF.md
 * - docs/CURSOR_HANDOFF.md
 *
 * Usage:
 *   node scripts/generate-handoff.js --write
 *   node scripts/generate-handoff.js --check
 */

const fs = require("node:fs");
const path = require("node:path");

function normalizeNewlines(value) {
  return value.replace(/\r\n/g, "\n");
}

function readFileOrEmpty(filePath) {
  return fs.existsSync(filePath)
    ? normalizeNewlines(fs.readFileSync(filePath, "utf8")).trim()
    : "";
}

function getNextUpLines(statePathAbs) {
  const raw = readFileOrEmpty(statePathAbs);
  const lines = raw.split(/\r?\n/);
  const start = lines.findIndex((line) => line.trim() === "## Next Up");
  if (start === -1) return [];
  const out = [];
  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith("## ")) break;
    if (line.trim().startsWith("- [ ] ")) {
      out.push(line.trim().replace("- [ ] ", "- "));
    }
    if (out.length >= 10) break;
  }
  return out;
}

function buildHandoff() {
  const repoRoot = process.cwd();
  const statePath = path.join(repoRoot, "docs", "SYSTEM_STATE.md");
  const state = readFileOrEmpty(statePath) || "docs/SYSTEM_STATE.md is missing.";
  const nextUp = fs.existsSync(statePath) ? getNextUpLines(statePath) : [];

  return [
    "## Nexus Prime — Agent Handoff (Compatibility Mirror)",
    "",
    "**Regenerated by:** `scripts/generate-handoff.js` (`npm run handoff:write`).",
    "Compatibility mirror path: `docs/AGENT_HANDOFF.md`.",
    "Compatibility copies are also written to `docs/CLAUDE_HANDOFF.md`, `docs/CODEX_HANDOFF.md`, and `docs/CURSOR_HANDOFF.md`.",
    "This file is a thin generated mirror of `docs/SYSTEM_STATE.md` plus pointers to the canonical 4-file core.",
    "It is not a source of unique truth.",
    "",
    "### Canonical Context Spine",
    "",
    "1. `AGENTS.md`",
    "2. `docs/SYSTEM_STATE.md`",
    "3. `docs/STANDARDS.md`",
    "4. `docs/PROJECT_BIBLE.md`",
    "",
    "Read `AGENTS.md` first. Use this handoff only for compatibility with older tooling.",
    "",
    "### Mirrored System State",
    "",
    state,
    "",
    "### Quick Queue",
    "",
    ...(nextUp.length ? nextUp : ["- Review `docs/SYSTEM_STATE.md` → `## Next Up`"]),
    "",
  ].join("\n");
}

const HANDOFF_OUTPUTS = [
  path.join(process.cwd(), "docs", "AGENT_HANDOFF.md"),
  path.join(process.cwd(), "docs", "CLAUDE_HANDOFF.md"),
  path.join(process.cwd(), "docs", "CODEX_HANDOFF.md"),
  path.join(process.cwd(), "docs", "CURSOR_HANDOFF.md"),
];

function main() {
  const args = process.argv.slice(2);
  const write = args.includes("--write");
  const check = args.includes("--check");
  if (!write && !check) {
    console.error("Usage: node scripts/generate-handoff.js --write|--check");
    process.exit(2);
  }

  const next = normalizeNewlines(buildHandoff()).trim() + "\n";

  if (check) {
    const stale = HANDOFF_OUTPUTS.filter((outPath) => {
      const current = fs.existsSync(outPath)
        ? normalizeNewlines(fs.readFileSync(outPath, "utf8"))
        : "";
      return normalizeNewlines(current) !== next;
    });
    if (stale.length) {
      console.error(
        `${stale.join(", ")} ${stale.length === 1 ? "is" : "are"} stale. Run: npm run handoff:write`,
      );
      process.exit(1);
    }
    console.log("Handoff OK: compatibility handoff files are up to date.");
    return;
  }

  for (const outPath of HANDOFF_OUTPUTS) {
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, next, "utf8");
    console.log(`Wrote ${outPath}`);
  }
}

main();
