import type {
  AssetKit,
  GeoDeltaSnapshot,
  ModelLabRun,
  RegistryItem,
  SecurityRun,
  SecurityScenario,
  WorkflowDefinition,
} from "@/lib/assimilation/types";
import { buildPassiveModelSafetyRun } from "@/lib/modelSafetyEvaluation";

const ISO_NOW = "2026-04-02T12:00:00.000Z";

export const DEFAULT_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "wf-morning-brief",
    name: "Morning Brief",
    description:
      "Run a multi-front briefing across macro, cyber, and geopolitics, then package a vault-ready operator memo.",
    theater: "watchlist",
    tags: ["briefing", "hq", "vault"],
    version: 3,
    updatedAt: ISO_NOW,
    approvalMode: "human_gate",
    nodes: [
      {
        id: "src-world",
        type: "source",
        title: "Source lattice",
        detail: "GDELT, prices, CVEs, and threat intel feed the same bundle.",
        x: 0,
        y: 0,
      },
      {
        id: "agent-orbit",
        type: "agent",
        title: "ORBIT synth",
        detail: "Frame the macro posture and global operating rhythm.",
        x: 1,
        y: 0,
      },
      {
        id: "transform-brief",
        type: "transform",
        title: "Brief compactor",
        detail: "Collapse source noise into five operator bullets.",
        x: 2,
        y: 0,
      },
      {
        id: "approval-sanction",
        type: "approval",
        title: "Sanction gate",
        detail: "Human review before the memo is archived or dispatched.",
        x: 3,
        y: 0,
      },
      {
        id: "sink-vault",
        type: "sink",
        title: "Vault export",
        detail: "Produce a saved brief with provenance, freshness, and severity.",
        x: 4,
        y: 0,
      },
    ],
    edges: [
      { id: "e1", from: "src-world", to: "agent-orbit", label: "raw feeds" },
      { id: "e2", from: "agent-orbit", to: "transform-brief", label: "analysis" },
      { id: "e3", from: "transform-brief", to: "approval-sanction", label: "draft brief" },
      { id: "e4", from: "approval-sanction", to: "sink-vault", label: "approved memo" },
    ],
  },
  {
    id: "wf-threat-sweep",
    name: "Threat Sweep",
    description:
      "Parallel cyber and recon sweep that produces a triage note, evidence pack, and sanction recommendation.",
    theater: "cyber",
    tags: ["cyber", "recon", "sweep"],
    version: 2,
    updatedAt: ISO_NOW,
    approvalMode: "approve_on_write",
    nodes: [
      {
        id: "src-cve",
        type: "source",
        title: "Threat source grid",
        detail: "CVE, CISA, threat intel, and passive DNS.",
        x: 0,
        y: 0,
      },
      {
        id: "agent-cipher",
        type: "agent",
        title: "CIPHER triage",
        detail: "Rank severity, exposure, and likely operator action.",
        x: 1,
        y: 0,
      },
      {
        id: "agent-nova",
        type: "agent",
        title: "NOVA corroboration",
        detail: "Cross-check public reporting and source credibility.",
        x: 2,
        y: 0,
      },
      {
        id: "sink-review",
        type: "sink",
        title: "Pending operator review",
        detail: "Queue evidence pack and triage note for sanction.",
        x: 3,
        y: 0,
      },
    ],
    edges: [
      { id: "e1", from: "src-cve", to: "agent-cipher", label: "telemetry" },
      { id: "e2", from: "agent-cipher", to: "agent-nova", label: "claims" },
      { id: "e3", from: "agent-nova", to: "sink-review", label: "evidence pack" },
    ],
  },
  {
    id: "wf-recon-dossier",
    name: "Recon Dossier",
    description:
      "Bundle passive lookup, headers, metadata, and OPSEC into one dossier-ready workflow.",
    theater: "infra",
    tags: ["recon", "headers", "metadata"],
    version: 1,
    updatedAt: ISO_NOW,
    approvalMode: "human_gate",
    nodes: [
      {
        id: "scheduler",
        type: "scheduler",
        title: "Mission cadence",
        detail: "Scheduled or manually triggered based on operator intent.",
        x: 0,
        y: 0,
      },
      {
        id: "source-passive",
        type: "source",
        title: "Passive collection",
        detail: "DNS, headers, metadata, and OPSEC checks.",
        x: 1,
        y: 0,
      },
      {
        id: "transform-dossier",
        type: "transform",
        title: "Dossier weave",
        detail: "Convert lookup results into a structured recon report.",
        x: 2,
        y: 0,
      },
      {
        id: "sink-download",
        type: "sink",
        title: "Download pack",
        detail: "Export a local bundle for offline review.",
        x: 3,
        y: 0,
      },
    ],
    edges: [
      { id: "e1", from: "scheduler", to: "source-passive", label: "dispatch" },
      { id: "e2", from: "source-passive", to: "transform-dossier", label: "normalized results" },
      { id: "e3", from: "transform-dossier", to: "sink-download", label: "artifact bundle" },
    ],
  },
];

export const DEFAULT_REGISTRY_ITEMS: RegistryItem[] = [
  {
    id: "reg-flowise",
    title: "Flowise",
    type: "workflow",
    summary: "Visual workflow-builder reference for node graphs, replay, and human checkpoints.",
    owner: "Nexus Core",
    custody: "Workflow Forge",
    costTier: "open_source",
    status: "ready",
    sourceUrl: "https://github.com/FlowiseAI/Flowise",
    license: "OSS - review upstream before reuse",
    tags: ["workflow", "graph", "agent"],
    reminder: "Keep Flowise import/export as optional compatibility only.",
    savedFilter: "forge",
    lastReviewedAt: ISO_NOW,
  },
  {
    id: "reg-moneyprinter",
    title: "MoneyPrinterV2",
    type: "playbook",
    summary: "Automation-pipeline reference for recipe-based output systems and mission bundling.",
    owner: "Ops Lab",
    custody: "Mission Foundry",
    costTier: "open_source",
    status: "watch",
    sourceUrl: "https://github.com/FujiwaraChoki/MoneyPrinterV2",
    license: "OSS - review upstream before reuse",
    tags: ["automation", "recipes", "deliverables"],
    reminder: "Do not inherit social-growth or monetization posture.",
    savedFilter: "foundry",
    lastReviewedAt: ISO_NOW,
  },
  {
    id: "reg-g0d",
    title: "G0DM0D3",
    type: "prompt",
    summary: "Red-team prompt mutation patterns for Blacksite Lab and injection stress-testing.",
    owner: "Blacksite",
    custody: "Prompt Lab",
    costTier: "open_source",
    status: "ready",
    sourceUrl: "https://github.com/elder-plinius/G0DM0D3",
    license: "OSS - review upstream before reuse",
    tags: ["red-team", "prompt-lab", "mutation"],
    reminder: "Operator-only; defensive use and model stress-testing only.",
    savedFilter: "blacksite",
    lastReviewedAt: ISO_NOW,
  },
  {
    id: "reg-crucix",
    title: "Crucix",
    type: "tool",
    summary: "One-command multi-source sweep reference for live bundle runs and delta tracking.",
    owner: "Intel",
    custody: "Sweep Engine",
    costTier: "open_source",
    status: "ready",
    sourceUrl: "https://github.com/calesthio/Crucix",
    license: "OSS - review upstream before reuse",
    tags: ["sweeps", "osint", "delta"],
    reminder: "Stay free-first and route through Nexus sources.",
    savedFilter: "sweeps",
    lastReviewedAt: ISO_NOW,
  },
  {
    id: "reg-dark-light",
    title: "Dark-Light Viewer",
    type: "dataset",
    summary: "Geospatial change-detection reference for before/after map splits and anomaly timelines.",
    owner: "Intel",
    custody: "Geo Delta",
    costTier: "license_check",
    status: "watch",
    sourceUrl: "https://github.com/bendobrown/Dark-Light-Viewer",
    license: "Review upstream data-license posture before productizing",
    tags: ["geo", "delta", "maps"],
    reminder: "Use existing public data first; keep paid imagery optional.",
    savedFilter: "geo-delta",
    lastReviewedAt: ISO_NOW,
  },
  {
    id: "reg-shelf",
    title: "Shelf.nu",
    type: "workflow",
    summary: "Registry reference for kits, custody, reminders, saved filters, and auditable asset state.",
    owner: "Registry",
    custody: "Archive + Resources",
    costTier: "open_source",
    status: "ready",
    sourceUrl: "https://github.com/Shelf-nu/shelf.nu",
    license: "AGPL - patterns only, no vendored code",
    tags: ["registry", "kits", "custody"],
    reminder: "Start digital-first before any physical gear tracking.",
    savedFilter: "registry",
    lastReviewedAt: ISO_NOW,
  },
  {
    id: "reg-gamedev",
    title: "GameDev Resources",
    type: "external_link",
    summary: "Curated free/open registry reference for tools, assets, tutorials, and license posture.",
    owner: "Field Manual",
    custody: "Resources",
    costTier: "free",
    status: "ready",
    sourceUrl: "https://github.com/Kavex/GameDev-Resources",
    license: "Reference list - always inspect individual item licenses",
    tags: ["resources", "free", "catalog"],
    reminder: "Every promoted link needs explicit license posture in Nexus.",
    savedFilter: "manual",
    lastReviewedAt: ISO_NOW,
  },
  {
    id: "reg-wstg",
    title: "OWASP WSTG",
    type: "playbook",
    summary: "Versioned scenario doctrine for route, auth, SSRF, input validation, and client-side testing.",
    owner: "Security",
    custody: "Doctrine",
    costTier: "open_source",
    status: "ready",
    sourceUrl: "https://github.com/OWASP/wstg",
    license: "CC BY-SA 4.0",
    tags: ["security", "wstg", "testing"],
    reminder: "Pin to WSTG-v42 until 5.0 stabilizes.",
    savedFilter: "doctrine",
    lastReviewedAt: ISO_NOW,
  },
  {
    id: "reg-aegis-brief-kit",
    title: "Homefront Brief Artifact Schema",
    type: "evidence_pack",
    summary: "Internal evidence pack format for vault-bound sweeps, briefs, and sanction-ready reports.",
    owner: "Nexus Core",
    custody: "Vault",
    costTier: "free_local",
    status: "draft",
    license: "Internal",
    tags: ["artifact", "vault", "schema"],
    lastReviewedAt: ISO_NOW,
    notes: "First wave ships as JSON-backed local artifacts through the persistence adapter.",
  },
];

export const DEFAULT_ASSET_KITS: AssetKit[] = [
  {
    id: "kit-operator-onboarding",
    title: "Operator Onboarding Kit",
    summary: "Manual, doctrine, workflow, and blacksite references for first-session setup.",
    itemIds: ["reg-flowise", "reg-g0d", "reg-wstg", "reg-gamedev"],
    owner: "HQ",
    status: "ready",
    reminder: "Review after any new surface ships.",
    lastReviewedAt: ISO_NOW,
  },
  {
    id: "kit-threat-sweep",
    title: "Threat Sweep Kit",
    summary: "Sweep engine, doctrine, and evidence-pack references for cyber monitoring.",
    itemIds: ["reg-crucix", "reg-wstg", "reg-aegis-brief-kit"],
    owner: "CIPHER",
    status: "ready",
    reminder: "Refresh after each major route or connector policy change.",
    lastReviewedAt: ISO_NOW,
  },
];

export const DEFAULT_SECURITY_SCENARIOS: SecurityScenario[] = [
  {
    id: "WSTG-v42-INFO-02",
    title: "Fingerprint exposed services and route classes",
    family: "Information gathering",
    source: "wstg-v42",
    status: "monitoring",
    owner: "CIPHER",
    evidence: "/api/project + route registry + release matrix",
    remediation: "Keep route visibility explicit and verify route policy coverage.",
    links: ["https://owasp.org/www-project-web-security-testing-guide/v42/"],
    updatedAt: ISO_NOW,
  },
  {
    id: "WSTG-v42-ATHN-01",
    title: "Authentication entry and token validation",
    family: "Authentication",
    source: "wstg-v42",
    status: "covered",
    owner: "CIPHER",
    evidence: "Auth gate + auth diagnostics + bearer-token validation flows",
    remediation: "Keep connect/logout host and cookie behavior regression-tested.",
    links: ["https://owasp.org/www-project-web-security-testing-guide/v42/"],
    updatedAt: ISO_NOW,
  },
  {
    id: "WSTG-v42-SESS-01",
    title: "Session management and cookie continuity",
    family: "Session",
    source: "wstg-v42",
    status: "covered",
    owner: "CIPHER",
    evidence: "127.0.0.1 auth fix + local cookie session helpers",
    remediation: "Keep auth/session route tests pinned to absolute hosts.",
    links: ["https://owasp.org/www-project-web-security-testing-guide/v42/"],
    updatedAt: ISO_NOW,
  },
  {
    id: "WSTG-v42-INPV-01",
    title: "Input validation across tools and auth payloads",
    family: "Input validation",
    source: "wstg-v42",
    status: "monitoring",
    owner: "ORBIT",
    evidence: "Guarded tools API + network guard + auth parser",
    remediation: "Add doctrine evidence whenever a new external input path ships.",
    links: ["https://owasp.org/www-project-web-security-testing-guide/v42/"],
    updatedAt: ISO_NOW,
  },
  {
    id: "WSTG-v42-CONF-04",
    title: "Header and transport posture",
    family: "Configuration",
    source: "wstg-v42",
    status: "covered",
    owner: "CIPHER",
    evidence: "Headers diagnostics + middleware route policy + CSP checks",
    remediation: "Keep policy additions centralized and auditable.",
    links: ["https://owasp.org/www-project-web-security-testing-guide/v42/"],
    updatedAt: ISO_NOW,
  },
  {
    id: "WSTG-v42-ATHZ-01",
    title: "Authorization boundaries on sensitive APIs",
    family: "Authorization",
    source: "wstg-v42",
    status: "attention",
    owner: "ORBIT",
    evidence: "Needs explicit doctrine entries for new assimilation APIs",
    remediation: "Audit all new persistence routes for read/write guardrails.",
    links: ["https://owasp.org/www-project-web-security-testing-guide/v42/"],
    updatedAt: ISO_NOW,
  },
  {
    id: "AI-PINJ-01",
    title: "Prompt injection resistance",
    family: "AI surface",
    source: "ai-surface",
    status: "covered",
    owner: "JANSKY",
    evidence: "Injection hardening block derived from Blacksite patterns",
    remediation: "Escalate new mutation families into Blacksite regression packs.",
    links: ["https://github.com/elder-plinius/G0DM0D3"],
    updatedAt: ISO_NOW,
  },
  {
    id: "AI-TOOL-02",
    title: "Tool misuse and outbound fetch boundaries",
    family: "AI surface",
    source: "ai-surface",
    status: "covered",
    owner: "CIPHER",
    evidence: "Rate limits + host allowlists + response caps + SSRF guards",
    remediation: "Add doctrine run whenever a new tool or adapter is introduced.",
    links: ["https://github.com/OWASP/wstg"],
    updatedAt: ISO_NOW,
  },
  {
    id: "AI-DATA-03",
    title: "Data leakage and artifact custody",
    family: "AI surface",
    source: "ai-surface",
    status: "monitoring",
    owner: "NOVA",
    evidence: "Vault/registry artifact plans and BYOK posture",
    remediation: "Annotate every artifact with provenance and export target.",
    links: ["https://github.com/Shelf-nu/shelf.nu"],
    updatedAt: ISO_NOW,
  },
  {
    id: "AI-APPROVAL-04",
    title: "Approval bypass and unsafe write escalation",
    family: "AI surface",
    source: "ai-surface",
    status: "covered",
    owner: "ORBIT",
    evidence: "Proposed edits and approval-gated writes across high-risk paths",
    remediation: "Mission Foundry defaults to human or write-only approvals.",
    links: ["https://github.com/FlowiseAI/Flowise"],
    updatedAt: ISO_NOW,
  },
  {
    id: "AI-MEM-05",
    title: "Persistence poisoning and cross-session carryover",
    family: "AI surface",
    source: "ai-surface",
    status: "attention",
    owner: "JANSKY",
    evidence: "Blacksite isolation and doctrine queue are now explicit but still early",
    remediation: "Keep lab sessions isolated from HQ memory until explicitly promoted.",
    links: ["https://github.com/elder-plinius/G0DM0D3"],
    updatedAt: ISO_NOW,
  },
];

export const DEFAULT_SECURITY_RUNS: SecurityRun[] = [
  {
    id: "run-auth-cookie",
    scenarioId: "WSTG-v42-SESS-01",
    result: "pass",
    summary: "127.0.0.1 connect flow retained the session cookie after host-normalization fixes.",
    createdAt: ISO_NOW,
  },
  {
    id: "run-ai-approval",
    scenarioId: "AI-APPROVAL-04",
    result: "warn",
    summary: "Approval posture is strong, but new assimilation APIs still need route-level audits.",
    createdAt: ISO_NOW,
  },
];

export const DEFAULT_MODEL_LAB_RUNS: ModelLabRun[] = [
  buildPassiveModelSafetyRun({
    id: "lab-orbit-inversion",
    title: "Boundary inversion tournament",
    mutationFamilies: ["boundary inversion", "authority spoofing"],
    createdAt: ISO_NOW,
    operatorNotes: "Baseline run used to seed the blacksite score rubric.",
    models: ["claude-opus", "local-qwen"],
    promptLabel: "Baseline",
  }),
];

export const DEFAULT_GEO_DELTA_SNAPSHOTS: GeoDeltaSnapshot[] = [
  {
    id: "geo-theater-eastmed",
    theater: "geopolitics",
    title: "East Med posture drift",
    summary: "Conflict, maritime, and narrative heat indicators moved together across the same theater.",
    severity: "medium",
    capturedAt: ISO_NOW,
    observations: [
      {
        id: "obs-eastmed-1",
        label: "Shipping congestion pulse",
        theater: "air-sea",
        severity: "medium",
        lat: 31.2,
        lon: 29.8,
        beforeLabel: "Nominal traffic",
        afterLabel: "Density spike",
        note: "Use ops map and maritime overlays as the primary evidence chain.",
      },
      {
        id: "obs-eastmed-2",
        label: "Narrative heat increase",
        theater: "geopolitics",
        severity: "medium",
        lat: 33.5,
        lon: 36.3,
        beforeLabel: "Scattered reporting",
        afterLabel: "Clustered reporting",
        note: "Correlates with conflict feed and world topic concentration.",
      },
    ],
  },
  {
    id: "geo-cyber-infra",
    theater: "infra",
    title: "Infra disruption watch",
    summary: "Cross-layer anomalies suggest increased cyber and operational attention on infrastructure-linked theaters.",
    severity: "high",
    capturedAt: ISO_NOW,
    observations: [
      {
        id: "obs-infra-1",
        label: "Critical CVE cluster",
        theater: "cyber",
        severity: "high",
        lat: 38.9,
        lon: -77,
        beforeLabel: "Routine volume",
        afterLabel: "Critical spike",
        note: "Pair with threat-intel and CISA advisories before escalation.",
      },
    ],
  },
];
